#!/bin/sh -e

# Include common wireless functions
source /etc/wifi/variscite-wireless

# Start WIFI hardware
wifi_start()
{
	run_scripts "/etc/wifi/variscite-wifi.d" "start"
}

# Stop WIFI hardware
# Note that on DART-MX8M this also stops Ethernet
wifi_stop()
{
	run_scripts "/etc/wifi/variscite-wifi.d" "stop"
}

###########################
#  Execution starts here  #
###########################
case $1 in
start)
	wifi_start
	;;
stop)
	wifi_stop
	;;
esac

exit 0
