# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "variscite-bsp-common"
BBFILE_PATTERN_variscite-bsp-common := "^${LAYERDIR}/"
BBFILE_PRIORITY_variscite-bsp-common = "16"

LAYERSERIES_COMPAT_variscite-bsp-common = " \
    dunfell \
    langdale \
    mickledore \
    scarthgap \
"

# TODO: Drop these lines when the external layers are compatible
LAYERSERIES_COMPAT_nxp-matter-baseline:append = " scarthgap"
LAYERSERIES_COMPAT_nxp-openthread:append = " scarthgap"

BBFILES_DYNAMIC += " \
    nxp-openthread:${LAYERDIR}/dynamic-layers/nxp-openthread/*/*/*.bb \
    nxp-openthread:${LAYERDIR}/dynamic-layers/nxp-openthread/*/*/*.bbappend \
    tpm-layer:${LAYERDIR}/dynamic-layers/tpm-layer/*/*/*.bb \
    tpm-layer:${LAYERDIR}/dynamic-layers/tpm-layer/*/*/*.bbappend \
"
